version: "3.9"

services:
  app:
    container_name: go-migrate-go
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${APP_PORT}:8080"
    volumes:
      - ./:/app  #เพื่อให้ container เห็นการแก้ไฟล์จาก host แบบเรียลไทม์ (hot reload ทำงานได้)
      - /app/tmp #เพื่อป้องกันไม่ให้ binary ที่ Air build ใน container หายไปเพราะการ mount ทับ
    environment:
      DATABASE_URL: "postgres://${DB_USERNAME}:${DB_PASSWORD}@${DB_HOST}:5432/${DB_DATABASE}?sslmode=disable"
      REDIS_URL: "redis://${REDIS_HOST}:${REDIS_PORT}"
    depends_on:
      database:
        condition: service_healthy
      cache:
        condition: service_healthy
    networks:
      - default
  
  database:
    container_name: go-migrate-database
    image: "postgres:17.6-alpine"
    ports:
      - "${DB_PORT}:5432"
    environment:
      POSTGRES_DB: "${DB_DATABASE}"
      POSTGRES_USER: "${DB_USERNAME}"
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
    volumes:
      - ./docker/postgres/data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USERNAME} -d ${DB_DATABASE} -h localhost"]
      # test: ["CMD-SHELL", "pg_isready -U ${DB_USERNAME}"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: always
    networks:
      - default

  cache:
    container_name: go-migrate-redis
    image: redis:7.4-alpine
    ports:
      - "${REDIS_PORT}:6379"
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: always
    networks:
      - default

  # migrate:
  #   image: migrate/migrate:v4.15.2
  #   container_name: migrate
  #   depends_on:
  #     database:
  #       condition: service_healthy
  #   volumes:
  #     - ./migrations:/migrations
  #   command: [
  #     "-path", "/migrations",
  #     "-database", "postgres://${DB_USERNAME}:${DB_PASSWORD}@${DB_HOST}:5432/${DB_DATABASE}?sslmode=disable",
  #     "up"
  #   ]
  #   networks:
  #     - default

networks:
  default:
    name: go-migrate-default